<section id="about" class="about">
        <div class="container">

          <div class="section-title">
            <h2>About</h2>
            <h3>Learn more about <span>koala</span></h3>
            <p><strong>koala</strong> was created to bring some utility features and quality-of-life improvements to
              Discord</p>
          </div>

          <div class="row content">
            <div class="col-lg-6">
              <p>
                See what <strong>koala</strong> has to offer
              </p>
              <ul>
                <li><i class="ri-check-double-line"></i> <strong>Image Manipulation</strong> to create your own funny
                  images </li>
                <li><i class="ri-check-double-line"></i> A <strong>Music System</strong> to play songs to your friends
                  in a call</li>
                <li><i class="ri-check-double-line"></i> <strong>Inspiring Quotes</strong> generated by <a
                    href="https://inspirobot.me/">InspiroBot</a> to brighten up your day</li>
              </ul>
            </div>
            <div class="col-lg-6 pt-4 pt-lg-0">
              <p>
                Obviously this is not it! There is many more features like <strong>browsing memes</strong> via Reddit,
                showing
                <strong>information and stats</strong> about you and the servers you are in and funny <strong>random
                  facts or jokes</strong>. Furthemore there is lots of new things <strong>actively in
                  development</strong>.
              </p>
              <a href="https://discord.gg/544CgsFeg2" class="btn-learn-more">Join Server</a>
            </div>
          </div>

        </div>
      </section>